service:
  name: image-api

custom:
  secrets: ${file(secrets.json)}
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  stage: ${self:custom.secrets.NODE_ENV}
  region: eu-north-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: 'arn:aws:s3:::${self:custom.secrets.S3_BUCKET_NAME}/*'
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}

functions:
  healthCheck:
    handler: src/functions/health-check.main
    events:
      - http:
          path: /
          method: get
          cors: true
  createAlbum:
    handler: src/functions/create-album.main
    events:
      - http:
          path: albums
          method: post
          cors: true
  createImage:
    handler: src/functions/create-image.main
    events:
      - http:
          path: albums/{id}/images
          method: post
          cors: true
          request:
            parameters:
              paths:
                id: true
  getImages:
    handler: src/functions/get-images.main
    events:
      - http:
          path: albums/{id}/images
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              querystrings:
                limit: true
                cursor: true

plugins:
  - serverless-webpack
  - serverless-offline
